networks:
  eventos-network:
    driver: bridge

services:
  eventos-telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: eventos-telegram-bot
    env_file: ./telegram-bot/.env
    environment:
      - URL_BASE=http://eventos-backend:8080/api/v1
    networks:
      - eventos-network
    ports:
      - "42068:443"
    depends_on:
      eventos-backend:
        condition: service_healthy

  eventos-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventos-backend
    env_file: .env # TODO: creo que las claves tendrían que ir en este archivo .env, que no se sube al repo
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - eventos-network
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  eventos-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventos-frontend
    ports:
      - "3000:80"
    networks:
      - eventos-network
    depends_on:
      eventos-backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:8080

  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nraboy
      MONGO_INITDB_ROOT_PASSWORD: password1234
    restart: unless-stopped
    networks:
      - eventos-network
    volumes:
      - mongo_data:/data/db # Guarda acá los datos. Si se borra el contenedor, los datos persisten.

  redis:
    image: redis:8.2
    container_name: eventos-redis
    command: [ "redis-server", "--save", "", "--appendonly", "no" ] # No guardo nada en disco
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - eventos-network

volumes:
  mongo_data:
