name: CI
on:
  push:
    branches: [main]
  pull_request:
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Maven Package
          run: mvn -B clean package -DskipTests
        - name: Maven Verify
          run: mvn -B clean verify

  check-format:
      name: Check Format
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Check Format
          run: |
            mvn formatter:validate
        - name: Find Comment
          continue-on-error: true
          if: success() || failure()
          uses: peter-evans/find-comment@v3
          id: fc
          with:
            issue-number: ${{ github.event.pull_request.number }}
            comment-author: "github-actions[bot]"
            body-includes: thiscommentistofindthisformatcomment
        - name: Create or update comment Failure
          continue-on-error: true
          if: failure()
          uses: peter-evans/create-or-update-comment@v4
          with:
            comment-id: ${{ steps.fc.outputs.comment-id }}
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              ❌ Code is not formatted! Please run `mvn formatter:validate`.

              <!-- thiscommentistofindthisformatcomment -->
            edit-mode: replace
        - name: Create or update comment Success
          continue-on-error: true
          if: ${{ success() && steps.fc.outputs.comment-id != null }}
          uses: peter-evans/create-or-update-comment@v4
          with:
            comment-id: ${{ steps.fc.outputs.comment-id }}
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              ✅ Code is now correctly formatted.

              <!-- thiscommentistofindthisformatcomment -->
            edit-mode: replace

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          
